quarkus:
  datasource:
    db-kind: postgresql
    devservices:
      image-name: postgres:10.7
      properties:
        - prepareThreshold: 0
        - preparedStatementCacheQueries: 0
        - autosave: conservative
  hibernate-orm:
    log:
      sql: true
    database:
      generation: drop-and-create
