quarkus:
  datasource:
    db-kind: postgresql
  hibernate-orm:
    log:
      sql: true
  flyway:
    schemas: quarkus
    migrate-at-start: true

'%dev':
  quarkus:
    config:
      profile:
        parent: 'common-dev'
    datasource:
      devservices:
        port: 5433

'%test':
  quarkus:
    config:
      profile:
        parent: 'common-dev'

'%WithOther':
  quarkus:
    config:
      profile:
        parent: 'common-dev'
    arc:
      selected-alternatives: com.github.renegrob.service.MyServiceOtherImpl