display:
  mach: 3
  unit:
    name: "mph"
    factor: 2.23694
quarkus:
  swagger-ui:
    always-include: true
    show-extensions: true
    show-common-extensions: true

  smallrye-openapi:
    store-schema-directory: openapi
    security-scheme: basic
    security-scheme-name: demo
    security-scheme-description: You login
    auto-add-tags: true

#  health:
#    openapi:
#      included: true
  openapi-mod:
    annotations:
      - "com.github.renegrob.MyDescription":
          bean: "com.github.renegrob.ApplyDescription"
          args:
            - "*${value}*"
mp:
  openapi:
    extensions:
      smallrye:
        operationIdStrategy: CLASS_METHOD
    filter: com.github.renegrob.openapi.OpenApiFilter
