quarkus:
  swagger-ui:
    always-include: true
    show-extensions: true
    show-common-extensions: true

  smallrye-openapi:
    store-schema-directory: openapi
    security-scheme: basic
    security-scheme-name: demo
    security-scheme-description: You login
    auto-add-tags: true

#  health:
#    openapi:
#      included: true
  openapi-mod:
    method-annotations:
      ".*":
        operationId: "#{className}_#{methodName}"
      "com.github.renegrob.MySummary":
        summary: "#{value} #{oldValue}"
        # pattern: "(.*)"
      "com.github.renegrob.MyRequirePrivileges":
        summary: "#{oldValue} requires: #{value}"
        # pattern: "(.*)"
      "com.github.renegrob.MyDescription":
        description: "*#{desc}*"
    parameter-annotations:
      "com.github.renegrob.MyDescription":
        description: "*#{desc}*"
      "com.github.renegrob.MyExample":
        example: "#{value}"
      "io.smallrye.common.constraint.NotNull":
        required: "true"


mp:
  openapi:
    extensions:
      smallrye:
        operationIdStrategy: CLASS_METHOD
    filter: com.github.renegrob.openapi.OpenApiFilter
