quarkus:
  swagger-ui:
    always-include: true
    show-extensions: true
    show-common-extensions: true

  smallrye-openapi:
    store-schema-directory: openapi
    security-scheme: basic
    security-scheme-name: demo
    security-scheme-description: You login
    auto-add-tags: true

#  health:
#    openapi:
#      included: true
  openapi-mod:
    annotations:
      "com.github.renegrob.MySummary":
        summary: "#{value} #{oldValue}"
      "com.github.renegrob.MyAnnotation":
        summary: "#{oldValue} requires: #{value}"
      "com.github.renegrob.MyDescription":
        description: "*#{desc}*"

mp:
  openapi:
    extensions:
      smallrye:
        operationIdStrategy: CLASS_METHOD
    filter: com.github.renegrob.openapi.OpenApiFilter
